sudo: false

language: node_js

node_js:
  - 6.11.2

env:
  - NON_INTERACTIVE=true

before_install:
  - npm list -g

install:
  - npm install

script:
  - node src/server.js &
  - npm run coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
