version: "3.3"
services:
  application:
    image: usgs/earthquake-design-ws:earthquake
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 30M
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - earthquake-network
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ws/designmaps/"]
      interval: 1m30s
      timeout: 10s
      retries: 20
    environment:
      # Retrieve environment from CICD secrets
    depends_on:
      - "database"
  database:
    image: mdillon/postgis:latest
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - earthquake-network
    volumes:
      - "/Users/jcaple/CODE/pgdata:/var/lib/postgresql/data/pgdata"

# Requires creation of swarm-level 'earthquake-network'
networks:
  earthquake-network:
    driver: overlay
    external: true


