version: "3.3"
services:
  application:
    image: ${IMAGE_NAME}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 30M
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - earthquake-network
    ports:
      - ${DEPLOY_PORT}:${PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/ws/designmaps/"]
      interval: 1m30s
      timeout: 10s
      retries: 20
    environment:
      - DB_ADMIN_HOST=${DB_ADMIN_HOST}
      - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD}
      - DB_ADMIN_PORT=${DB_ADMIN_PORT}
      - DB_ADMIN_USER=${DB_ADMIN_USER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_SCHEMA_DETERMINISTIC=${DB_SCHEMA_DETERMINISTIC}
      - DB_SCHEMA_PROBABILISTIC=${DB_SCHEMA_PROBABILISTIC}
      - DB_SCHEMA_RISK_COEFFICIENT=${DB_SCHEMA_RISK_COEFFICIENT}
      - DB_SCHEMA_TSUBL=${DB_SCHEMA_TSUBL}
      - DETERMINISTIC_SERVICE_URL=${DETERMINISTIC_SERVICE_URL}
      - MOUNT_PATH=${MOUNT_PATH}
      - PORT=${PORT}
      - PROBABILISTIC_SERVICE_URL=${PROBABILISTIC_SERVICE_URL}
      - RISK_COEFFICIENT_SERVICE_URL=${RISK_COEFFICIENT_SERVICE_URL}
      - TSUBL_SERVICE_URL=${TSUBL_SERVICE_URL}
    depends_on:
      - "database"
  database:
    image: mdillon/postgis:latest
    environment:
      - PGDATA=${PGDATA_CONTAINER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    networks:
      - earthquake-network
    volumes:
      - ${PGDATA_HOST}:${PGDATA_CONTAINER}

networks:
  earthquake-network:
    driver: overlay